-- MySQL Script generated by MySQL Workbench
-- Sun Jul  4 17:49:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbinformacion_vuelo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbinformacion_vuelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbinformacion_vuelo` DEFAULT CHARACTER SET utf8 ;
USE `dbinformacion_vuelo` ;

-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`country` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`passenger` (
  `id_passenger` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `document_type` VARCHAR(50) NOT NULL,
  `number_document` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NULL,
  `country_id_country` INT NOT NULL,
  PRIMARY KEY (`id_passenger`),
  INDEX `fk_pasajero_pais1_idx` (`country_id_country` ASC) ,
  CONSTRAINT `fk_pasajero_pais1`
    FOREIGN KEY (`country_id_country`)
    REFERENCES `dbinformacion_vuelo`.`country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`origin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`origin` (
  `id_origin` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_origin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`destination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`destination` (
  `id_destination` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_destination`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`itinerary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`itinerary` (
  `id_itinerario` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `origin_id_origin` INT NOT NULL,
  `destination_id_destation` INT NOT NULL,
  PRIMARY KEY (`id_itinerario`),
  INDEX `fk_itinerario_origen1_idx` (`origin_id_origin` ASC) ,
  INDEX `fk_itinerario_destino1_idx` (`destination_id_destation` ASC) ,
  CONSTRAINT `fk_itinerario_origen1`
    FOREIGN KEY (`origin_id_origin`)
    REFERENCES `dbinformacion_vuelo`.`origin` (`id_origin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itinerario_destino1`
    FOREIGN KEY (`destination_id_destation`)
    REFERENCES `dbinformacion_vuelo`.`destination` (`id_destination`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`reserve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`reserve` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `code_reserve` VARCHAR(10) NULL,
  `date` DATE NULL,
  `total_pay` INT NULL,
  `itinerary_id_itinerary` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_itinerario1_idx` (`itinerary_id_itinerary` ASC) ,
  CONSTRAINT `fk_reserva_itinerario1`
    FOREIGN KEY (`itinerary_id_itinerary`)
    REFERENCES `dbinformacion_vuelo`.`itinerary` (`id_itinerario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`pay` (
  `id_pay` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `value_pay` INT NOT NULL,
  `type_proof_payment` VARCHAR(45) NOT NULL,
  `number_proof_payment` VARCHAR(45) NOT NULL,
  `passenger_id_passenger` INT NOT NULL,
  `reserve_id_reserve` INT NOT NULL,
  PRIMARY KEY (`id_pay`),
  INDEX `fk_pago_pasajero_idx` (`passenger_id_passenger` ASC) ,
  INDEX `fk_pago_reserva1_idx` (`reserve_id_reserve` ASC) ,
  CONSTRAINT `fk_pago_pasajero`
    FOREIGN KEY (`passenger_id_passenger`)
    REFERENCES `dbinformacion_vuelo`.`passenger` (`id_passenger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_reserva1`
    FOREIGN KEY (`reserve_id_reserve`)
    REFERENCES `dbinformacion_vuelo`.`reserve` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`airport` (
  `id_airport` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country_id_country` INT NOT NULL,
  PRIMARY KEY (`id_airport`),
  INDEX `fk_aureopuerto_pais1_idx` (`country_id_country` ASC) ,
  CONSTRAINT `fk_aureopuerto_pais1`
    FOREIGN KEY (`country_id_country`)
    REFERENCES `dbinformacion_vuelo`.`country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`airline` (
  `id_airline` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_airline`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`plane` (
  `id_plane` INT NOT NULL,
  `registration_number` VARCHAR(45) NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  `airline_id_airline` INT NOT NULL,
  PRIMARY KEY (`id_plane`),
  INDEX `fk_avion_aerolinea1_idx` (`airline_id_airline` ASC) ,
  CONSTRAINT `fk_avion_aerolinea1`
    FOREIGN KEY (`airline_id_airline`)
    REFERENCES `dbinformacion_vuelo`.`airline` (`id_airline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`rate` (
  `id_rate` INT NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(45) NOT NULL,
  `value_pay` INT NULL,
  PRIMARY KEY (`id_rate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`seat` (
  `id_seat` INT NOT NULL AUTO_INCREMENT,
  `row` VARCHAR(8) NULL,
  `letter` VARCHAR(8) NULL,
  `location` VARCHAR(45) NULL,
  `seat_type` VARCHAR(45) NULL,
  `plane_id_plane` INT NOT NULL,
  PRIMARY KEY (`id_seat`),
  INDEX `fk_seat_plane1_idx` (`plane_id_plane` ASC) ,
  CONSTRAINT `fk_seat_plane1`
    FOREIGN KEY (`plane_id_plane`)
    REFERENCES `dbinformacion_vuelo`.`plane` (`id_plane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`flight` (
  `id_flight` INT NOT NULL,
  `flight_number` VARCHAR(45) NOT NULL,
  `flying_type` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NULL,
  `rate_id_rate` INT NOT NULL,
  `plane_id_plane` INT NOT NULL,
  `airport_id_airport` INT NOT NULL,
  `reserva_id_reserva` INT NOT NULL,
  `seat_id_seat` INT NOT NULL,
  PRIMARY KEY (`id_flight`),
  INDEX `fk_vuelo_tarifa1_idx` (`rate_id_rate` ASC) ,
  INDEX `fk_vuelo_avion1_idx` (`plane_id_plane` ASC) ,
  INDEX `fk_vuelo_aureopuerto1_idx` (`airport_id_airport` ASC) ,
  INDEX `fk_vuelo_reserva1_idx` (`reserva_id_reserva` ASC) ,
  INDEX `fk_flight_seat1_idx` (`seat_id_seat` ASC) ,
  CONSTRAINT `fk_vuelo_tarifa1`
    FOREIGN KEY (`rate_id_rate`)
    REFERENCES `dbinformacion_vuelo`.`rate` (`id_rate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelo_avion1`
    FOREIGN KEY (`plane_id_plane`)
    REFERENCES `dbinformacion_vuelo`.`plane` (`id_plane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelo_aureopuerto1`
    FOREIGN KEY (`airport_id_airport`)
    REFERENCES `dbinformacion_vuelo`.`airport` (`id_airport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vuelo_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `dbinformacion_vuelo`.`reserve` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_seat1`
    FOREIGN KEY (`seat_id_seat`)
    REFERENCES `dbinformacion_vuelo`.`seat` (`id_seat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
