-- MySQL Script generated by MySQL Workbench
-- Mon Jun 28 16:19:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbflight_information
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbflight_information
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbflight_information` DEFAULT CHARACTER SET utf8 ;
USE `dbflight_information` ;

-- -----------------------------------------------------
-- Table `dbflight_information`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`country` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`passenger` (
  `id_passenger` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `document_type` VARCHAR(50) NOT NULL,
  `number_document` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NULL,
  `country_id_country` INT NOT NULL,
  PRIMARY KEY (`id_passenger`),
  INDEX `fk_passenger_country1_idx` (`country_id_country` ASC) ,
  CONSTRAINT `fk_passenger_country1`
    FOREIGN KEY (`country_id_country`)
    REFERENCES `dbflight_information`.`country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`destination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`destination` (
  `id_destination` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_destination`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`origin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`origin` (
  `id_origin` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_origin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`itinerary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`itinerary` (
  `id_itinerario` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `destination_id_destination` INT NOT NULL,
  `origin_id_origin` INT NOT NULL,
  PRIMARY KEY (`id_itinerario`),
  INDEX `fk_itinerary_destination1_idx` (`destination_id_destination` ASC) ,
  INDEX `fk_itinerary_origin1_idx` (`origin_id_origin` ASC) ,
  CONSTRAINT `fk_itinerary_destination1`
    FOREIGN KEY (`destination_id_destination`)
    REFERENCES `dbflight_information`.`destination` (`id_destination`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itinerary_origin1`
    FOREIGN KEY (`origin_id_origin`)
    REFERENCES `dbflight_information`.`origin` (`id_origin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`reserve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`reserve` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `code_reserve` VARCHAR(10) NULL,
  `date` DATE NULL,
  `total_pay` INT NULL,
  `itinerary_id_itinerario` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserve_itinerary1_idx` (`itinerary_id_itinerario` ASC) ,
  CONSTRAINT `fk_reserve_itinerary1`
    FOREIGN KEY (`itinerary_id_itinerario`)
    REFERENCES `dbflight_information`.`itinerary` (`id_itinerario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`pay` (
  `id_pay` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `value_pay` INT NOT NULL,
  `type_proof_payment` VARCHAR(45) NOT NULL,
  `number_proof_payment` VARCHAR(45) NOT NULL,
  `passenger_id_passenger` INT NOT NULL,
  `reserve_id_reserva` INT NOT NULL,
  PRIMARY KEY (`id_pay`),
  INDEX `fk_pay_passenger1_idx` (`passenger_id_passenger` ASC) ,
  INDEX `fk_pay_reserve1_idx` (`reserve_id_reserva` ASC) ,
  CONSTRAINT `fk_pay_passenger1`
    FOREIGN KEY (`passenger_id_passenger`)
    REFERENCES `dbflight_information`.`passenger` (`id_passenger`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pay_reserve1`
    FOREIGN KEY (`reserve_id_reserva`)
    REFERENCES `dbflight_information`.`reserve` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`airport` (
  `id_airport` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country_id_country` INT NOT NULL,
  PRIMARY KEY (`id_airport`),
  INDEX `fk_airport_country1_idx` (`country_id_country` ASC) ,
  CONSTRAINT `fk_airport_country1`
    FOREIGN KEY (`country_id_country`)
    REFERENCES `dbflight_information`.`country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`airline` (
  `id_airline` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_airline`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `dbflight_information`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`seat` (
  `id_seat` INT NOT NULL AUTO_INCREMENT,
  `row` VARCHAR(8) NULL,
  `letter` VARCHAR(8) NULL,
  `location` VARCHAR(45) NULL,
  `seat_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_seat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`plane` (
  `id_plane` INT NOT NULL,
  `registration_number` VARCHAR(45) NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  `seat_id_seat` INT NOT NULL,
  `airline_id_airline` INT NOT NULL,
  PRIMARY KEY (`id_plane`),
  INDEX `fk_plane_seat1_idx` (`seat_id_seat` ASC) ,
  INDEX `fk_plane_airline1_idx` (`airline_id_airline` ASC) ,
  CONSTRAINT `fk_plane_seat1`
    FOREIGN KEY (`seat_id_seat`)
    REFERENCES `dbflight_information`.`seat` (`id_seat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plane_airline1`
    FOREIGN KEY (`airline_id_airline`)
    REFERENCES `dbflight_information`.`airline` (`id_airline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`rate` (
  `id_rate` INT NOT NULL AUTO_INCREMENT,
  `class` VARCHAR(45) NOT NULL,
  `value_pay` INT NULL,
  PRIMARY KEY (`id_rate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbflight_information`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbflight_information`.`flight` (
  `id_flight` INT NOT NULL,
  `flight_number` VARCHAR(45) NOT NULL,
  `flying_type` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NULL,
  `reserve_id_reserva` INT NOT NULL,
  `rate_id_rate` INT NOT NULL,
  `plane_id_plane` INT NOT NULL,
  `airport_id_airport` INT NOT NULL,
  PRIMARY KEY (`id_flight`),
  INDEX `fk_flight_reserve1_idx` (`reserve_id_reserva` ASC) ,
  INDEX `fk_flight_rate1_idx` (`rate_id_rate` ASC) ,
  INDEX `fk_flight_plane1_idx` (`plane_id_plane` ASC) ,
  INDEX `fk_flight_airport1_idx` (`airport_id_airport` ASC) ,
  CONSTRAINT `fk_flight_reserve1`
    FOREIGN KEY (`reserve_id_reserva`)
    REFERENCES `dbflight_information`.`reserve` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_rate1`
    FOREIGN KEY (`rate_id_rate`)
    REFERENCES `dbflight_information`.`rate` (`id_rate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_plane1`
    FOREIGN KEY (`plane_id_plane`)
    REFERENCES `dbflight_information`.`plane` (`id_plane`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_airport1`
    FOREIGN KEY (`airport_id_airport`)
    REFERENCES `dbflight_information`.`airport` (`id_airport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
