-- MySQL Script generated by MySQL Workbench
-- Mon Jun 28 16:19:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbinformacion_vuelo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbinformacion_vuelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbinformacion_vuelo` DEFAULT CHARACTER SET utf8 ;
USE `dbinformacion_vuelo` ;

-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`aerolinea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`aerolinea` (
  `id_aerolinea` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aerolinea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = '	';


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`asiento` (
  `id_asiento` INT NOT NULL AUTO_INCREMENT,
  `fila` VARCHAR(8) NULL DEFAULT NULL,
  `letra` VARCHAR(8) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_asiento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_asiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`aureopuerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`aureopuerto` (
  `id_aureopuerto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pais_idpais` INT NOT NULL,
  PRIMARY KEY (`id_aureopuerto`),
  INDEX `fk_aureopuerto_pais1_idx` (`pais_idpais` ASC),
  CONSTRAINT `fk_aureopuerto_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `dbinformacion_vuelo`.`pais` (`id_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`avion` (
  `id_avion` INT NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `capacidad` VARCHAR(45) NOT NULL,
  `aerolinea_id_aerolinea` INT NOT NULL,
  PRIMARY KEY (`id_avion`),
  INDEX `fk_avion_aerolinea1_idx` (`aerolinea_id_aerolinea` ASC),
  CONSTRAINT `fk_avion_aerolinea1`
    FOREIGN KEY (`aerolinea_id_aerolinea`)
    REFERENCES `dbinformacion_vuelo`.`aerolinea` (`id_aerolinea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`destino` (
  `id_destino` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_destino`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`origen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`origen` (
  `id_origen` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_origen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`itinerario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`itinerario` (
  `id_itinerario` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `origen_id_origen` INT NOT NULL,
  `destino_id_destino` INT NOT NULL,
  PRIMARY KEY (`id_itinerario`),
  INDEX `fk_itinerario_origen1_idx` (`origen_id_origen` ASC),
  INDEX `fk_itinerario_destino1_idx` (`destino_id_destino` ASC),
  CONSTRAINT `fk_itinerario_destino1`
    FOREIGN KEY (`destino_id_destino`)
    REFERENCES `dbinformacion_vuelo`.`destino` (`id_destino`),
  CONSTRAINT `fk_itinerario_origen1`
    FOREIGN KEY (`origen_id_origen`)
    REFERENCES `dbinformacion_vuelo`.`origen` (`id_origen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`pasajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`pasajero` (
  `id_pasajero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `pais_idpais` INT NOT NULL,
  PRIMARY KEY (`id_pasajero`),
  INDEX `fk_pasajero_pais1_idx` (`pais_idpais` ASC),
  CONSTRAINT `fk_pasajero_pais1`
    FOREIGN KEY (`pais_idpais`)
    REFERENCES `dbinformacion_vuelo`.`pais` (`id_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `codigo_reserva` VARCHAR(10) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  `itinerario_id_itinerario` INT NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_itinerario1_idx` (`itinerario_id_itinerario` ASC),
  CONSTRAINT `fk_reserva_itinerario1`
    FOREIGN KEY (`itinerario_id_itinerario`)
    REFERENCES `dbinformacion_vuelo`.`itinerario` (`id_itinerario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `saldo` INT NOT NULL,
  `tipo_comprobante` VARCHAR(45) NOT NULL,
  `num_comprobante` VARCHAR(45) NOT NULL,
  `pagocol` VARCHAR(45) NOT NULL,
  `pasajero_idpasajero` INT NOT NULL,
  `reserva_id_reserva` INT NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pago_pasajero_idx` (`pasajero_idpasajero` ASC),
  INDEX `fk_pago_reserva1_idx` (`reserva_id_reserva` ASC),
  CONSTRAINT `fk_pago_pasajero`
    FOREIGN KEY (`pasajero_idpasajero`)
    REFERENCES `dbinformacion_vuelo`.`pasajero` (`id_pasajero`),
  CONSTRAINT `fk_pago_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `dbinformacion_vuelo`.`reserva` (`id_reserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`tarifa` (
  `id_tarifa` INT NOT NULL AUTO_INCREMENT,
  `clase` VARCHAR(45) NOT NULL,
  `valor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_tarifa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbinformacion_vuelo`.`vuelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbinformacion_vuelo`.`vuelo` (
  `id_vuelo` INT NOT NULL,
  `numero_vuelo` VARCHAR(45) NOT NULL,
  `tipo_vuelo` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `tarifa_id_tarifa` INT NOT NULL,
  `avion_id_avion` INT NOT NULL,
  `asiento_id_asiento` INT NOT NULL,
  `aureopuerto_id_aureopuerto` INT NOT NULL,
  `reserva_id_reserva` INT NOT NULL,
  PRIMARY KEY (`id_vuelo`),
  INDEX `fk_vuelo_tarifa1_idx` (`tarifa_id_tarifa` ASC),
  INDEX `fk_vuelo_avion1_idx` (`avion_id_avion` ASC),
  INDEX `fk_vuelo_asiento1_idx` (`asiento_id_asiento` ASC),
  INDEX `fk_vuelo_aureopuerto1_idx` (`aureopuerto_id_aureopuerto` ASC),
  INDEX `fk_vuelo_reserva1_idx` (`reserva_id_reserva` ASC),
  CONSTRAINT `fk_vuelo_asiento1`
    FOREIGN KEY (`asiento_id_asiento`)
    REFERENCES `dbinformacion_vuelo`.`asiento` (`id_asiento`),
  CONSTRAINT `fk_vuelo_aureopuerto1`
    FOREIGN KEY (`aureopuerto_id_aureopuerto`)
    REFERENCES `dbinformacion_vuelo`.`aureopuerto` (`id_aureopuerto`),
  CONSTRAINT `fk_vuelo_avion1`
    FOREIGN KEY (`avion_id_avion`)
    REFERENCES `dbinformacion_vuelo`.`avion` (`id_avion`),
  CONSTRAINT `fk_vuelo_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `dbinformacion_vuelo`.`reserva` (`id_reserva`),
  CONSTRAINT `fk_vuelo_tarifa1`
    FOREIGN KEY (`tarifa_id_tarifa`)
    REFERENCES `dbinformacion_vuelo`.`tarifa` (`id_tarifa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
